name: Push to Gigalixir
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
        env:
          GIGALIXIR_EMAIL: ${{secrets.GIGALIXIR_EMAIL}}
          GIGALIXIR_API_KEY: ${{secrets.GIGALIXIR_API_KEY}}
          GIGALIXIR_APP_NAME: ${{secrets.GIGALIXIR_APP_NAME}}
      - run: git push -f gigalixir HEAD:refs/heads/master
