name: Deploy to Gigalixir
on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      
      - env:
          GIGALIXIR_EMAIL: ${{ secrets.GIGALIXIR_EMAIL }}
          GIGALIXIR_API_KEY: ${{ secrets.GIGALIXIR_API_KEY }}
          GIGALIXIR_APP_NAME: ${{ secrets.GIGALIXIR_APP_NAME }}
        run: git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git

      - run: git push -f gigalixir HEAD:refs/heads/master
